### ISSUE TITLE
Can't start it

### ISSUE THREAD

**Issue by Minipada** [Spantree/docker-sugarcrm#12]
Thanks for the repo, nice wok
I couldn't run it, I tried with `docker-compose up`  but install is blocked:

```
Warning: mysql_connect(): Server sent charset (255) unknown to the client. Please, report to the developers in /var/www/html/include/database/MysqlManager.php on line 482

Warning: mysql_connect(): Server sent charset unknown to the client. Please, report to the developers in /var/www/html/include/database/MysqlManager.php on line 482

Warning: mysql_connect(): Server sent charset (255) unknown to the client. Please, report to the developers in /var/www/html/include/database/MysqlManager.php on line 482

Warning: mysql_connect(): Server sent charset unknown to the client. Please, report to the developers in /var/www/html/include/database/MysqlManager.php on line 482
Please fix the following errors before proceeding:

The provided database host, username, and/or password is invalid, and a connection to the database could not be established. Please enter a valid host, username and password
```

**Comment by mdwaidari** [comment]
This problem can be solved in the Mysql database server "--default-authentication-plugin=mysql_native_password"
docker run -it --name mysql -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=some_password -e MYSQL_DATABASE=crm -e MYSQL_ROOT_HOST='%' mysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

**Comment by Minipada** [comment]
Thanks for the answer. I'm not using it anymore and assume you answered the question. So I will close the issue and the maintainers can reopen if they feel the need!
