### ISSUE TITLE
Newbie question - 

### ISSUE THREAD

**Issue by brandontamm** [Spantree/docker-sugarcrm#2]
In your directions, #2) states to "Run docker-compose up from the root of this project." Again, I apologize for the newbie question, but I am trying to find the "root" directory of your project after running "docker pull spantree/sugarcrm"

Where is the default directory docker "pulled" your project to? 

Thanks for your help!

**Comment by freethejazz** [comment]
Hey @tabr0201, Did you close this issue because you figured it out? Just want to make sure it doesn't get lost if you're still having trouble.

**Comment by brandontamm** [comment]
oh - sorry I posted it to docker instead of github because it's not really a problem with your code, but more a question regarding the process you mentioned in docker. do you prefer to answer here or there?

so where I'm at - I still never figured out where the project was pulled to so I could browse to the folder and run the docker-compose. I cloned the project from github to a directory on my mac and ran docker-compose from there though and got it all up and it was working flawlessly. I think I kinda "hacked" it to get it working lol

thank you for responding :)

**Comment by divideby0** [comment]
Hi @tabr0201, just seeing this. So the `docker-compose` example was meant to be run after a `git clone`, not `docker pull`. That part of the documentation was mostly meant for people that wanted to modify the Dockerfile or init scripts.

I copied the instructions from the README directly into dockerhub but I'll update to clarify.

**Comment by brandontamm** [comment]
Thank you!
